// This file was generated by gir (https://github.com/gtk-rs/gir @ 8b9d0bb)
// from gir-files (https://github.com/gtk-rs/gir-files @ 77d1f70)
// DO NOT EDIT

mod font;
pub use self::font::Font;
pub use self::font::FontExt;

mod font_map;
pub use self::font_map::FontMap;
pub use self::font_map::FontMapExt;

pub mod functions;

#[doc(hidden)]
pub mod traits {
    pub use super::FontExt;
    pub use super::FontMapExt;
}
